### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by FlorianBirnkammer** [jbbarth/redmine_better_crossprojects#18]
Hi,

I'm really looking forward to use your plugin, but unfortunately I still have some installation issue.
When I try to migrate the plugin using
```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```
 I get following error:
```
rake aborted!
NameError: uninitialized constant ActiveSupport::Reloader
/var/www/redmine/plugins/redmine_better_crossprojects/init.rb:3:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/www/redmine/lib/redmine/plugin.rb:155:in `block in load'
/var/www/redmine/lib/redmine/plugin.rb:146:in `each'
/var/www/redmine/lib/redmine/plugin.rb:146:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/activesupport-4.2.11/lib/active_support/notifications.rb:166:in `instrument'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/engine.rb:651:in `load_config_initializer'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/engine.rb:615:in `each'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `each'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/application.rb:328:in `require_environment!'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/railties-4.2.11/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/redmine/.rvm/gems/ruby-2.4.5/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
/home/redmine/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```
Both redmine_base_select2 and redmine_base_deface are installed and I didn't have any issues with those.

Do you have any idea what's going wrong? Do you need me to provide more information?

Thank you!

**Comment by nanego** [comment]
Hello.
The last version of the plugin is only compatible with Redmine 4.
What is your current version?

**Comment by FlorianBirnkammer** [comment]
Thanks for replying so quickly! I’m working with version 3.4.x. Is there a way to get crossprojects running on my system?

Von: vrobert <notifications@github.com>
Gesendet: Dienstag, 26. Februar 2019 16:32
An: jbbarth/redmine_better_crossprojects <redmine_better_crossprojects@noreply.github.com>
Cc: Birnkammer Florian <florian.birnkammer@unibw.de>; Author <author@noreply.github.com>
Betreff: Re: [jbbarth/redmine_better_crossprojects] NameError (#18)


Hello.
The last version of the plugin is only compatible with Redmine 4.
What is your current version?

**Comment by nanego** [comment]
Yes, with Redmine 3.4, you have to use this release:
https://github.com/jbbarth/redmine_better_crossprojects/releases/tag/v3.4.6

**Comment by FlorianBirnkammer** [comment]
Now it works, thank you. Great Plugin by the way
