### ISSUE TITLE
Error while exporting issues in csv

### ISSUE THREAD

**Issue by tantic** [jbbarth/redmine_better_crossprojects#20]
Hi,

when i activate the plugin, i got an error when i try to export issues in csv format.
Here is the log

```
NoMethodError (super: no superclass method `csv_content' for #<IssuesController:0x007f36d4fe3870>):
  plugins/redmine_better_crossprojects/lib/redmine_better_crossprojects/queries_helper_patch.rb:39:in `csv_content'
  plugins/redmine_tags/lib/redmine_tags/patches/queries_helper_patch.rb:32:in `csv_content_with_redmine_tags'
  plugins/redmine_better_crossprojects/lib/redmine_better_crossprojects/queries_helper_patch.rb:39:in `csv_content'
  app/helpers/queries_helper.rb:280:in `block (3 levels) in query_to_csv'
  app/helpers/queries_helper.rb:280:in `map'
  app/helpers/queries_helper.rb:280:in `block (2 levels) in query_to_csv'
  app/helpers/queries_helper.rb:279:in `each'
  app/helpers/queries_helper.rb:279:in `block in query_to_csv'
  lib/redmine/export/csv.rb:44:in `generate'
  lib/redmine/export/csv.rb:26:in `generate'
  app/helpers/queries_helper.rb:275:in `query_to_csv'
  app/controllers/issues_controller.rb:66:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:46:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```
If i disable the plugin, everything works fine.

Here is my configuration
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    development
  Database adapter               PostgreSQL
  
   redmine_better_crossprojects   3.4.6

I saw that you fixed this in the commit 15b1b1b89b3f4573b6df0a3590fb8e1c05b82e4d but it does'nt work for me i still have the message super: no superclass method

Is there anything else I should do?

Thanks very much

**Comment by tantic** [comment]
Note, if i change the line 39 in the file lib/redmine_better_crossprojects/queries_helper_patch.rb to get back to the old version
```
  +        value = column.value_object(project)
   -       return super
```
it works again
